sonar.projectKey=assignment-2
sonar.sources=src
sonar.tests=test-case
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://localhost:9000
sonar.token=sqp_e7b8b5524a97ea1adeb9a8198686cdb3b509e82f